"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR.parent / '.env' if 'BASE_DIR' in dir() else None)
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# اضافه کردن ریشه‌ی پروژه به sys.path تا shared_lib قابل import باشه
sys.path.insert(0, str(BASE_DIR.parent))

# بارگذاری .env (پروژه‌ی monorepo — فایل در ریشه‌ی پروژه است)
try:
    from dotenv import load_dotenv as _ld
    _ld(BASE_DIR.parent / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-7espy+8c8zk9l_+$om6h^!43i-ncp$s4mjtf0=fu@x#%f5x_i_',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] or ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.AdminAccessMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/diako/login/'
LOGIN_REDIRECT_URL = '/diako/dashboard/'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent / 'shared-data' / 'bot.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

UNFOLD = {
    "SITE_TITLE": "دیاکو",
    "SITE_HEADER": "پنل مدیریت دیاکو",
    "SITE_SYMBOL": "vpn_lock",
    "SCRIPTS": [
        lambda _: "/static/js/dark-mode.js",
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "داشبورد",
                "items": [
                    {
                        "title": "خانه",
                        "icon": "home",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "زیرساخت",
                "separator": True,
                "items": [
                    {
                        "title": "سرورها",
                        "icon": "dns",
                        "link": "/admin/dashboard/servers/",
                    },
                    {
                        "title": "پلن‌ها",
                        "icon": "sell",
                        "link": "/admin/dashboard/plans/",
                    },
                ],
            },
            {
                "title": "فروش",
                "separator": True,
                "items": [
                    {
                        "title": "سفارش‌ها",
                        "icon": "shopping_cart",
                        "link": "/admin/dashboard/orders/",
                    },
                    {
                        "title": "شارژ حساب",
                        "icon": "payments",
                        "link": "/admin/dashboard/topuprequests/",
                    },
                    {
                        "title": "کدهای تخفیف",
                        "icon": "local_offer",
                        "link": "/admin/dashboard/discountcodes/",
                    },
                ],
            },
            {
                "title": "کاربران",
                "separator": True,
                "items": [
                    {
                        "title": "کاربران",
                        "icon": "group",
                        "link": "/diako/users/",
                    },
                    {
                        "title": "تراکنش‌ها",
                        "icon": "account_balance_wallet",
                        "link": "/admin/dashboard/transactions/",
                    },
                    {
                        "title": "دعوت دوستان",
                        "icon": "share",
                        "link": "/admin/dashboard/referrals/",
                    },
                ],
            },
            {
                "title": "پشتیبانی و محتوا",
                "separator": True,
                "items": [
                    {
                        "title": "تیکت‌ها",
                        "icon": "support_agent",
                        "link": "/admin/dashboard/tickets/",
                    },
                    {
                        "title": "آموزش‌ها",
                        "icon": "school",
                        "link": "/admin/dashboard/tutorials/",
                    },
                    {
                        "title": "سوالات متداول",
                        "icon": "help",
                        "link": "/admin/dashboard/faqs/",
                    },
                ],
            },
            {
                "title": "تنظیمات",
                "separator": True,
                "items": [
                    {
                        "title": "تنظیمات سیستم",
                        "icon": "settings",
                        "link": "/admin/dashboard/settings/",
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "base": {
            "50":  "oklch(97% .008 232)",
            "100": "oklch(93% .015 230)",
            "200": "oklch(86% .022 228)",
            "300": "oklch(76% .028 228)",
            "400": "oklch(60% .036 230)",
            "500": "oklch(47% .040 232)",
            "600": "oklch(36% .038 234)",
            "700": "oklch(26% .034 236)",
            "800": "oklch(19% .030 237)",
            "900": "oklch(14% .025 238)",
            "950": "oklch(9%  .020 240)",
        },
        "primary": {
            "50":  "oklch(97% .016 194)",
            "100": "oklch(93% .040 194)",
            "200": "oklch(87% .080 194)",
            "300": "oklch(80% .135 194)",
            "400": "oklch(74% .180 194)",
            "500": "oklch(74% .200 194)",
            "600": "oklch(63% .180 194)",
            "700": "oklch(52% .155 194)",
            "800": "oklch(42% .125 194)",
            "900": "oklch(32% .095 194)",
            "950": "oklch(21% .065 194)",
        },
        "font": {
            "subtle-light":    "var(--color-base-500)",
            "subtle-dark":     "var(--color-base-400)",
            "default-light":   "var(--color-base-700)",
            "default-dark":    "var(--color-base-200)",
            "important-light": "var(--color-base-900)",
            "important-dark":  "var(--color-base-50)",
        },
    },
}
