services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: diako-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - shared_data:/shared-data
    depends_on:
      - panel

  panel:
    build:
      context: .
      dockerfile: Dockerfile.panel
    container_name: diako-panel
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PANEL_PORT:-8000}:8000"
    volumes:
      - shared_data:/shared-data
      - static_data:/app/staticfiles

volumes:
  shared_data:
  static_data:
